config/routes.rb
HtBattle::Application.routes.draw do
  devise_for :users

  root :to => 'battles#index'
  resources :hashtags
  resources :battles do
    post 'start'
    post 'end'
  end

  get 'present.js' => "battles#present"
end

app/models/battle.rb
class Battle < ActiveRecord::Base
  attr_accessible :name, :brand_1_hashtag, :brand_1_count, :brand_2_hashtag, :brand_2_count
  @@count = 1

  def self.set_name(brand_1,brand_2)
    this.name = "#{brand_1} " + " vs. " + "#{brand_2}"
  end

end

app/models/hash_tag.rb
class HashTag < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/hashtag_battle.rb
require 'twitter'

module HashtagBattle

  def self.get_stream()

    client = Twitter::Streaming::Client.new do |config|
      config.consumer_key        = "AJrghs2Q74I09aAUAoegK3t6G"
      config.consumer_secret     = "tK2YdY8ACrYSgtUb50z2N8gbYFK2iGar6mYMuLztZQGxaahkDe"
      config.access_token        = "351152791-gSBD8CXSKOaj3rs2cYNEOkVjBVkzrq7VpF9v9lvG"
      config.access_token_secret = "61lJYCMJ8DP8NlanYoQR8cevIGInHKpOtblKYLxD5ibeI"
    end

    client.sample do |object|
      puts object.text if object.is_a?(Twitter::Tweet)
    end

  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/battle_controller.rb
class BattleController < ApplicationController

  def index
    @battle = Battle.new
    #battle1 = HashtagBattle.new
    Resque.enqueue(HashtagBattle,1)
    # @count = HashtagBattle.counter
    # fork {
    #HashtagBattle.get_stream()
    # }
  end

  def new
    render :text => HashtagBattle.counter
  end

end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController

  def index
  end

  def create
    # create object with passed params, tell db object is running
    @battle = Battle.new(params[:battle])
    @battle.running = true

    puts params[:battle]

    # save everyone
    @battle.save!

    # Enqueue to Resque
    Resque.enqueue(HashtagBattle, @battle.id, params[:battle][:brand_1_hashtag], params[:battle][:brand_2_hashtag])


    # redirect to battle, "show" battle
    redirect_to battle_path(@battle.id)
    
  end

  def show
    @battle = Battle.find(params[:id])
  end

  def new
  end

  def time
  end

  def present
    @battle = Battle.where("id = ?", params[:battle_id])

    respond_to do |format|
      format.js
    end
    # redirect_to battle_path(@battle.id)
  end

  def end
    # tell db object is not running

    battle = Battle.find_by_id(params[:battle_id])
    battle.running = false

    Battle.transaction do
      battle.save!
    end

    # dequeue everything from resque
    Resque.queues.each do |q|
      Resque.redis.del "queue:#{q}"
    end

    # redir to home
    redirect_to :root
  end

end

app/controllers/hashtags_controller.rb
class HashtagsController < ApplicationController

  def index
    @hashtags = Battle.where("id = ?", params[:battle_id])

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battle_helper.rb
module BattleHelper
end

app/helpers/hashtags_helper.rb
module HashtagsHelper
end

app/views/battle/index.html.haml
%h1
  Hash Tag Battle

= form_for :battle, :url => new_battle_path do |f|
  = f.label :brand_1_hashtag
  = f.text_field :brand_1_hashtag
  = f.label :brand_2_hashtag
  = f.text_field :brand_2_hashtag
  = f.submit "Begin Battle", :class => "btn btn-primary"

= link_to "Start Counting" , :class => "btn btn-primary"
%br
= @count

app/views/battles/_present.html.haml
%h1
%div#battle{ :data => {:id => @battle.id }}

%p
  Brand 1 Count

= battle.brand_1_count

%p
  Brand 2 Count
= battle.brand_2_count

app/views/battles/index.html.haml
%h1
  Hash Tag Battle

= form_for :battle, :url => battles_path do |f|
  = f.label :brand_1_hashtag
  \#
  = f.text_field :brand_1_hashtag
  = f.label :brand_2_hashtag
  \#
  = f.text_field :brand_2_hashtag
  = f.submit "Begin Battle", :class => "btn btn-primary"

app/views/battles/new.html.haml
%h1
  Create a New Battle

= form_for :battle, :url => battle_index_path do |f|
  = f.label :brand_1_hashtag
  = f.text_field :brand_1_hashtag
  = f.label :brand_2_hashtag
  = f.text_field :brand_2_hashtag
  = f.submit "Begin Battle", :class => "btn btn-primary"

app/views/battles/present.js.haml
//TODO: if time
%p
  here

:plain
  console.log('hi')

/ :plain
/   $('#battle').html("#{escape_javascript(render("present", :battle => @battle ))}");

app/views/battles/show.html.haml
%h1
  Running Battles!


= render :partial => "present", locals: {:battle => @battle}

= button_to "End Counting", battle_end_path(@battle.id), :class => "btn btn-danger"

app/views/battles/time.js.haml
:plain
  alert("times will be updated here.")

app/views/hashtags/_hashtag.html.haml
/ %div.hashtag{ :data => {:id => @battle.id }}
/   = @battle.brand_1_count

app/views/hashtags/index.js.haml
:plain
  $('#hashtags').html("#{escape_javascript(raw @hashtags.brand_1_hashtag)}");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HtBattle</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top:40px">
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Hash Tag Battle</a>
      <div class="nav-collapse">
        <ul class="nav">
        </ul>
      </div>
    </div>
  </div>
</div>
<%= yield %>

</body>
</html>